# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [2]:
# Tu respuesta aquí
nombre = "Cristhian"
edad = 34

print("Hola mi nombre es", nombre, "y tengo", edad, "años.")

Hola mi nombre es Cristhian y tengo 34 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [16]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí

print ("- El primer numero es:", numeros[0], "y el último numero es:", numeros[5])

print("- Los tres primeros numeros son:", numeros[0:3])

numeros.insert(6, 99)
print("- La lista de numeros con el nuevo numero es:", numeros)




- El primer numero es: 10 y el último numero es: 15
- Los tres primeros numeros son: [10, 25, 3]
- La lista de numeros con el nuevo numero es: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [19]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6.0:
    print("El estudiante", estudiante["nombre"], "está aprobado.")
else:
    print("El estudiante", estudiante["nombre"], "está reprobado.")

El estudiante Carlos está reprobado.


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [2]:
# Tu respuesta aquí
base = 5
altura = 7

area =(base * altura/2)
print("El area del triángulo es:", area)


El area del triángulo es: 17.5


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [25]:
# Tu respuesta aquí
comprehension = [x**2 for x in range(1, 11)]
print("Los cuadrados de los números del 1 al 10 son:", comprehension)


Los cuadrados de los números del 1 al 10 son: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [26]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [53]:
# Tu respuesta aquí
array_v = np.array([1.5, 2.5, 3.5, 4.5])
matriz = np.zeros((3, 4))
array_lins = np.linspace(0, 1 , 6)

print("* Primer arreglo es:\n", array_v)
print(array_v.dtype, array_v.shape)
print("-----------------------------------")
print("* Matriz es:\n", matriz)
print(matriz.dtype, matriz.shape)
print("-----------------------------------")
print("* Arreglo lineal es:\n", array_lins)
print(array_lins.dtype, array_lins.shape)

* Primer arreglo es:
 [1.5 2.5 3.5 4.5]
float64 (4,)
-----------------------------------
* Matriz es:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64 (3, 4)
-----------------------------------
* Arreglo lineal es:
 [0.  0.2 0.4 0.6 0.8 1. ]
float64 (6,)


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [63]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz_corre = a.reshape(3, 4)
print("* Matriz 3 x 4:\n", matriz_corre)
print("-----------------------------------")
print(f"* El numero minimo es: {matriz_corre.min()}\n* El numero maximo es: {matriz_corre.max()}\n* La posición del valor maximo es: {matriz_corre.argmax()}")


* Matriz 3 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------
* El numero minimo es: 1
* El numero maximo es: 12
* La posición del valor maximo es: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [68]:
# Tu respuesta aquí
array_1 = np.random.randint(1, 20, 5)
array_2 = np.random.randint(1, 20, 5)

suma = array_1 + array_2
resta = array_1 - array_2
multi = array_1 * array_2

print("* El resultado de la suma es:\n", suma)
print("* El resultado de la resta es:\n", resta)
print("* El resultado de la multiplicación es:\n", multi)

* El resultado de la suma es:
 [31 25 19 18  3]
* El resultado de la resta es:
 [  5  -7  -3 -14  -1]
* El resultado de la multiplicación es:
 [234 144  88  32   2]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [70]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

notas_m = notas[notas >= 6]
print("Las notas mayores o iguales a 6.0 son:", notas_m)

Las notas mayores o iguales a 6.0 son: [ 8.5  6.   9.2  7.8 10. ]
